name: smartbreath
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  google_fonts: ^2.3.2
  latlong: ^0.6.1
  syncfusion_flutter_sliders: ^20.1.52
  flutter_native_splash: ^2.1.6
  font_awesome_flutter: ^10.1.0
  introduction_screen: ^3.0.2
  flutter_switch: ^0.3.2
  animated_toggle_switch: ^0.2.3
  shared_preferences: ^2.0.13
  google_maps_flutter: ^2.1.4
  location: ^4.3.0
  geolocator: ^8.2.0
  hive: ^2.1.0
  lottie: ^1.3.0
  dio: ^4.0.6
  flutter_polyline_points: ^1.0.0
  path_provider: ^2.0.9
  provider: ^6.0.2
  search_map_location: ^0.0.5
  firebase_auth: ^3.3.17
  cloud_firestore: ^3.1.14
  fluttertoast: ^8.0.9
  flutter_locales: ^2.0.1
  google_nav_bar: ^5.0.6
  share_files_and_screenshot_widgets: ^1.0.6
  flutter_rating_bar: ^4.0.0
  flutter_blue: ^0.8.0
  circular_menu: ^1.2.3
  image_picker: ^0.8.5+3
  image_cropper: ^2.0.2
  firebase_storage: ^10.2.15
  email_auth: ^1.0.0
  google_sign_in: ^5.3.1
  flutter_local_notifications: ^9.5.3+1
  rxdart: ^0.26.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_native_splash:
  background_image: "assets/image/splash_screen.png"
  android: true
  ios: true
  fullscreen: true

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/image/
  - assets/locales/en.json
  - assets/locales/tr.json
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Bangers
      fonts:
        - asset: assets/fonts/Bangers-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
